model_list:
  - model_name: "*"
    litellm_params:
      model: openai/local
      api_base: http://127.0.0.1:7776/v1
      api_key: "any"
    model_info:
      max_input_tokens: 95536
      max_context_length: 95536

litellm_settings:
  drop_params: true
